### ISSUE TITLE
NX300 bricked  I need a dnloader.bin file.

### ISSUE THREAD

**Issue by kiltel** [ge0rg/samsung-nx-hacks#16]
I need a dnloader.bin file. Service manual samsung nx 300 <a href=https://zapodaj.net/c7c87452b045f.png.html>recover.png</a>

**Comment by ge0rg** [comment]
This is from the Samsung GPL dump NX300-1.4.zip, subdirectory TIZEN/project/bootloader:
https://op-co.de/tmp/bootloader-1.4.zip
