### ISSUE TITLE
Interval Mode to create Timelapses

### ISSUE THREAD

**Issue by fab343** [ge0rg/samsung-nx-hacks#17]
Is there a possibilty with this hack to finally do Interval Mode Timelpases with a NX3000 camera?

**Comment by naums** [comment]
This should be possible quite easily, if you are somewhat technically inclined. You can put an autoexec.sh bash-script on to the camera and repeatedly issue a button-press event when a certain time has passed. See [wiki](https://github.com/ge0rg/samsung-nx-hacks/wiki/KeyBindings). 

Making this visible in the UI is an insane amount of work, no one in their right mind would do. So, be my guest.

**Comment by ge0rg** [comment]
We don't know of any way to run our own code on the NX3000. Unfortunately. You can however use the micro USB port for a remote shutter: https://antibore.wordpress.com/2013/04/30/diy-remote-shutter-release-for-samsung-nx20-nx210-and-nx1000-cameras/

This could probably be re-created around an ESP-8266 to make a wifi shutter for older NX models.
