### ISSUE TITLE
Source Files for NX2000

### ISSUE THREAD

**Issue by hunkreborn** [ge0rg/samsung-nx-hacks#20]
Hello, does anyone have a backup copy of the Source Files for NX2000? I had it in 2014, for some reason its not available anymore in the opensource.samsung.com site, theres only source for NX1 camera.
The file name of the package is nx2000-open-code.zip.
Thanks!

**Comment by ge0rg** [comment]
Sorry the only firmware I have decentralized backup of is `NX300-1.4.zip`. Let me know if you are interested in a copy of that.

**Comment by hunkreborn** [comment]
Hey, actually I jut got a reply for my request from open source samsung, they reuploaded the NX2000 file for a while so I could download it! Thats really nice! 

I'm having a hard time figuring out how to edit di-camera-app-nx2000 to extend the movie file limit. 
So far I was able to bypass the 20min cap using telnet and prefman, but its still limited by the file size! 

Should I open an issue or can I use this one?

**Comment by TheNitek** [comment]
Isn't the file size limit caused by the file system rather then the camera firmware?

**Comment by hunkreborn** [comment]
I don't think so, my SD was already exFat even before trýing to hack the camera, I have already changed the "REC_LIMIT" by using prefman.

```
nx2000:/# prefman info 1_
------------------------------------------------
     _Offset    Size    Name    [application]
------------------------------------------------
 0x00000308    0004    `APPPREF_B_DISABLE_MOVIE_REC_LIMIT`
```

```
nx2000:/# prefman set 1 0x308 l 1
[application] in memory:
value = 1 (0x00000001)
```


Just found out a way to "de-brick" the camera in case of bad firmware, following the NX300 repair manual. 

I'm willing to test mods in my camera, would appreciate a help in this case. 
Thanks!
