### ISSUE TITLE
can't find the nx300 source code anymore

### ISSUE THREAD

**Issue by jaecktec** [ge0rg/samsung-nx-hacks#22]
hey, I'm looking for the nx300 source. It is not available under samsung.com. Does anyone have it somewhere in their archives and would make it available somewhere? :)

**Comment by GrayWolfson** [comment]
NX300.tar
https://cloud.mail.ru/public/cMfr/EAoWykQ1z

**Comment by jaecktec** [comment]
thank you very much

**Comment by jaecktec** [comment]
found the original source: https://opensource.samsung.com/uploadSearch?searchValue=nx300
