### ISSUE TITLE
NX300 firmware downgrade

### ISSUE THREAD

**Issue by MartijnBraam** [ge0rg/samsung-nx-hacks#26]
My NX300 has a 1.45 firmware so I cannot use the autoexec.sh functionality. It seems like the older firmware versions have completely disappeared from the internet.

Does anyone have a backup of an old firmware version?

**Comment by ge0rg** [comment]
I'm not aware of a need to downgrade the NX300 (without M), but you can find older firmware versions here: https://nxfiles.nx.tc/files/NX300/Firmware/
