### ISSUE TITLE
Video output for live preview (Video) for Samsung NX500

### ISSUE THREAD

**Issue by Fickert07** [ge0rg/samsung-nx-hacks#8]
I am using a Samsung NX500 for aerial photography. I used av for live video to a ground station. This provides low latencies and delays. The firmware currenly only allows to record in 1080p at 24fps while using live video out, but can record up to 4k in 24fps which is what I really want. Is there a way around this? unlink the live video out and filming resolution?

**Comment by ge0rg** [comment]
Hey, this is a thing that is actively developed over at the https://github.com/ottokiksmaler/nx500_nx1_modding project. It seems the differences between NX300 and NX500 are big enough to warrant different repos and projects, so please read up the docs available there.
