### ISSUE TITLE
Samsung NX500 4k cropping. 

### ISSUE THREAD

**Issue by Fickert07** [ge0rg/samsung-nx-hacks#9]
Has this poorly chosen feature been tackled yet?

I wish I could help out but my coding experience is extremely small (can barely tune a quadcopter)

**Comment by ge0rg** [comment]
Hey, this is a thing that is actively developed over at the https://github.com/ottokiksmaler/nx500_nx1_modding project. It seems the differences between NX300 and NX500 are big enough to warrant different repos and projects, so please read up the docs available there.
